### ISSUE TITLE
no planes files

### ISSUE THREAD

**Issue by gblack007** [LRMPUT/PlaneSLAM#2]
Thanks for your work! I try to run the PlaneSLAM, but there is no planes file if fold "../res/", can you provide it for me? thanks again!!!

**Comment by jwietrzykowski** [comment]
Hi,

I've added exemplary "planes.txt" file.

Best regards

**Comment by gblack007** [comment]
Thanks for your reply! I have learned your paper and project carefully, I am also interested in the plane-based slam problem. In the g2o tool, the plane's representation used in the optimization step is the normal's orientation and the distance from the origin, which has also only three parameters. Have you ever tested its performance compared to your minimal representation?

**Comment by jwietrzykowski** [comment]
Hi,

no, I haven't compared those two representations. However, I've made a lot of experiments and comparing planes directly in any representation is flawed by the different nature of distance and orientation. In my research, I use now metric that evaluates point-plane distance, since any error based on real-world sensor measurement can be transformed to that form.

Best regards
